

</HEAD>
<BODY BGCOLOR=#FFFFFF link="#0066CC" LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0>
<!-- ImageReady Slices (newbanner.jpg) -->
<table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td rowspan="2"><TABLE WIDTH="100%" BORDER=0 CELLPADDING=0 CELLSPACING=0 bgcolor="#CC0000">
	<TR>
		<TD width="58" ROWSPAN=2 align="left">
			<div align="left"><IMG SRC="images/seal.jpg" ALT="LOGO" align="left"></div></TD>
		<TD COLSPAN=6 align="left" bgcolor="#CC0000">
			<div align="left"><IMG SRC="images/newbanner_02.jpg" WIDTH=390 HEIGHT=26 ALT="TXDPS"></div></TD>
	    <TD WIDTH=184 align="left" valign="middle" bgcolor="#CC0000">&nbsp;</TD>
	    <TD WIDTH=184 align="left" valign="middle" bgcolor="#CC0000"><input type="text" name="q" size="25" maxlength="255" value=""/></TD>
	    <TD WIDTH=65 align="left" valign="middle" bgcolor="#CC0000"><input type="image" name="btnG" src="images/search.jpg" alt="Search Button"/></TD>
	    <TD WIDTH=86 ROWSPAN=2 align="left" valign="top" bgcolor="#CC0000"><table>
          <tr>
            <td valign=top>&nbsp;            </td>
            <td valign="top"> <a href="/search/advancedsearch.asp?site=crawl&client=crawl&proxystylesheet=http://www.dps.texas.gov/includes/styles/internetstylesheet.xslt&output=xml_no_dtd&restrict=ER&proxycustom=%3CADVANCED/%3E"><font size="1"><strong>Advanced
                  Search</strong></font></a><font size="1">&nbsp; </font> </td>
          </tr>
        </table></TD>
    </TR>
	<TR>
		<TD width="38"><img src="images/newbanner_04.jpg" alt="home" name="Image8" width="37" height="17" border="0"></TD>
		<TD width="73"><img src="images/newbanner_05.jpg" alt="about us" name="Image9" width="72" height="17" border="0"></TD>
		<TD width="80"><img src="images/newbanner_06.jpg" alt="employment" name="Image10" width="79" height="17" border="0"></TD>
		<TD width="99">
	      <img src="images/newbanner_07.jpg" alt="online services" name="Image11" width="98" height="17" border="0"></TD>
		<TD width="44"><img src="images/newbanner_08.jpg" alt="news" name="Image12" width="43" height="17" border="0"></TD>
		<TD width="62">
			<div align="left"><IMG SRC="images/newbanner_09.jpg" WIDTH=61 HEIGHT=17 ALT=""></div></TD>
        <TD WIDTH=184 valign="top" bgcolor="#CC0000">&nbsp;</TD>
        <TD WIDTH=184 valign="top" bgcolor="#CC0000"><input type="hidden" name="site" value="crawl"/>
        <input type="hidden" name="client" value="crawl"/>
        <input type="hidden" name="proxystylesheet" value=http://www.dps.texas.gov/includes/styles/internetstylesheet.xslt />
        <input type="hidden" name="output" value="xml_no_dtd"/>
        <input type="hidden" name="getfields" value="title.keywords"/>
        <input type="hidden" name="restrict" value="ER"/><form method="get" action="/search/searchresults.aspx">
</form></TD>
	    <TD WIDTH=65 valign="top" bgcolor="#CC0000"></TD>
	</TR>
	<TR>
	  <TD colspan="11" align="left"><img src="images/btm.jpg" height="5" width="100%"></TD>
	  </TR>
</TABLE></td>
    <td width="25%" bgcolor="#CC0000"></td>
  </tr>
  <tr>
    <td bgcolor="#CC0000" valign="bottom"><img src="images/btm.jpg" width="100%" height="5"></td>
  </tr>
</table>


<!-- End ImageReady Slices -->
<!-- Search My Google Search Appliance -->

<!-- Search My Google Search Appliance-->
