<table width="100%" border="0">
<tr>
<td><a href="http://www.dps.texas.gov/"><img
src="/includes/images/mainpage.gif" alt="main page" width="72"
height="21" border="0" /></a></td>
<td>&nbsp;</td>
<td><a href="/siteindex.htm"><img
src="/includes/images/siteindex.gif" alt="site index" width="74"
height="21" border="0" /></a></td>
<td>&nbsp;</td>
<td><a href="/divisions.htm"><img
src="/includes/images/divisions.gif" alt="divisions" width="68"
height="21" border="0" /></a></td>
<td>&nbsp;</td>
<td><a href="/onserv.htm"><img
src="/includes/images/onlineservices.jpg" alt="online services"
width="109" height="21" border="0" /></a></td>
<td>&nbsp;</td>
<td><a
href="/administration/staff_support/human_resources/jobs/jobsearch.asp">
<img src="/includes/images/employment.gif" alt="employment"
width="88" height="21" border="0" /></a></td>
<td>&nbsp;</td>
<td><a href="/news.htm"><img
src="/includes/images/news.jpg" alt="news" width="45" height="21"
border="0" /></a></td>
<td>&nbsp;</td>
</tr>
</table>