<div>
<div align="center"><img src="/images/seperatorwide.jpg" alt="&quot;&quot;" width="720" height="20" /></div>
<br />
<div align="center"	>
 | <a href="/about.htm">About DPS</a> |
<a href="/administration/staff_support/human_resources/ADA.htm">ADA Compliance</a> |
<a href="s/SitePolicies.htm">Site Policies</a> |
<a href="/contact.htm">Contact Information</a> | 
<a href="/LBB/" title="Legislative Appropriations Request for FY 2010 and 2011">LAR</a> | 
<a href="/OperatingBudgetFY2010.pdf" title="New browser window to open the Operating Budget for Fiscal Year 2010 (pdf)" target="_blank">Operating Budget (PDF)</a> | 
<a href="/geninfo.htm">General Information</a> | 
<a href="http://www.texasonline.com/" title="Texas Online" target="_blank">Texas Online</a> |
<a href="http://www.tsl.state.tx.us/trail" title="Texas Records And Information Locator" target="_blank">TRAIL</a> | 
<a href="http://tsiec.region49.org/" title="Texas State Interoperability Executive Committee" target="_blank">TSIEC</a>  |
<br/>
 |

<a href="/exchange" title="Outlook Web Access">Outlook Web Access</a> |
<a href="/pia.htm" title="Public Information Act">Public Information Act</a> |
<a href="/privacy.htm" title="DPS Privacy Policy">Privacy Policy</a> |
<a href="/compact/" title="Information about the Agency">Compact with Texans</a> | 
<a href="/director_staff/public_information/openrecords.htm" title="File an Open Records Request">Open Records</a> |
<a href="http://www.survey.utexas.edu/txdps/" target="_blank" title="Customer Survey">Customer Survey</a> |
<a href="/OIG/complaint.htm" title="How to file a complaint against specific DPS personnel">Personnel Complaint Process</a> <a href="/OIG/complaint-esp.htm" title="Como presentar una queja">(Español)</a>  |
</div><br />

<div align="center"><img src="http://www.dps.texas.gov/images/seperator2wide.jpg" alt="&quot;&quot;" width="422" height="25" /></div>
<br />


<div align="center"
	style="font:9px verdana, arial, helvetica, sans-serif;
	padding-top: 4px;
	padding-right: 0px;
	padding-bottom: 10px;
	color: #666666;">
Texas Department of Public Safety
5805 North Lamar Blvd. Austin, Texas 78752-4422&nbsp;<br />
 P O Box 4087 Austin, Texas 78773-0001<br />
 (512) 424-2000<br />
&copy; 2000Texas Department of Public Safety.
<br />
<br />
 If an employee or division provided outstanding service<br />
 or if you have suggestions for improvement, please let us know.
Take our <a href="http://www.survey.utexas.edu/txdps/" target="_blank">Customer Survey.</a>
<br />
<br />
Pursuant to Section 552.301(c),Government Code, the <a href="/director_staff/public_information/">Public Information Office</a> has been designated to receive all electronic mail requests for
public information. <br />
The Department is not responsible for
responding to electronic mail requests sent to any electronic mail
address other than the address for the Public Information
Office.<br />
</div>
<br />
<br />
</div>