<!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WPB5R5"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WPB5R5');</script>
<!-- End Google Tag Manager -->

<script src="/js/dropdown.js"></script>

<nav>
<ul id="nav" >
	
	<li><a href="http://www.dps.texas.gov/index.htm" ><strong>DPS Home</strong></a></li>

	<!-- second button -->
  	<li ><a href="/onserv.htm"><strong>Services</strong> </a>
    	<ul >
	 		<li ><a href="/administration/crime_records/pages/index.htm" class="subMenuIndicator" >Crime Records</a>
				<ul >
			  		<li><a href="https://records.txdps.state.tx.us/DpsWebsite/CriminalHistory/">Criminal History Search</a></li>
			  		<li><a href="/administration/crime_records/pages/applicantfingerprintservices.htm">Fingerprint Services</a></li>
			  		<li><a href="https://records.txdps.state.tx.us/SexOffender/">Sex Offender Search</a></li>
				</ul>
		  	</li>
		  	<li><a href="/CriminalInvestigations/index.htm" class="subMenuIndicator">Criminal Investigations</a>
		  		<ul >
	 				<li><a href="/polygraph/index.htm">Polygraph School</a></li>
				</ul>
		  	</li>
			<li><a href="/DriverLicense/index.htm" class="subMenuIndicator" >Driver License/ID Home</a>
				<ul >
					<li><a href="/DriverLicense/dlfork.aspx?action=change">Address Change</a></li>
					<li><a href="/DriverLicense/driverrecords.htm">Driver Record Request</a></li>
					<li><a href="/administration/driver_licensing_control/rolodex/search.asp">Office Locations</a></li>
					<li><a href="/DriverLicense/dlfork.aspx?action=renew">Renewal</a></li>
			 	</ul>
			</li>
			<li><a href="/LawEnforcementSupport/" class="subMenuIndicator" >Law Enforcement Support</a>
		  		<ul >
		  			<li><a href="/BalLab">Breath Alcohol Laboratory</a></li>
					<li><a href="/LawEnforcementSupport/communications/index.htm">Communications</a> </li>
					<li><a href="/CrimeLaboratory/index.htm">Crime Laboratory</a></li>
					<li><a href="/ucr/indexnibrs.htm">NIBRS/TIBRS</a> </li>
				</ul>
			</li>
		
			<li><a href="/RSD/" class="subMenuIndicator" >Regulatory Services</a>
		  		<ul >
					<li><a href="/rsd/cap/index.htm" >Capitol Access Pass</a> </li>
					<li><a href="/rsd/cops/index.htm" >Commissioned Online Prescription System</a> </li>
					<li><a href="/rsd/CUP/index.htm" >Compassionate Use Program</a> </li>
					<li><a href="/rsd/ltc/index.htm" >Handgun Licensing</a> </li>
					<li><a href="/rsd/IgnitionInterlock/index.htm" >Ignition Interlock</a> </li>
					<li><a href="/rsd/Peyote/index.htm" >Peyote</a> </li>
					<li><a href="/rsd/Precursor/index.htm">Precursor Laboratory Apparatus</a></li>
					<li><a href="/rsd/psb/index.htm">Private Security</a></li>
					<li><a href="/RSD/TexasMetalsProgram/index.htm">Texas Metals Program</a></li>
					<li><a href="/rsd/vi/index.htm">Vehicle Inspection</a></li>
				</ul>
	   		</li>
	  		<li><a href="/LawEnforcementSupport/txLESOPrgm.htm">Texas LESO Program</a></li>
  		</ul>
  	</li>
  
	<!-- third button -->
  	<li><a href="/employment/index.htm"> <strong>Employment </strong></a></li>
  
	<!-- fourth button -->
  	<li><a href="/about.htm"> <strong>About Us </strong></a>
		<ul >
			<li><a href="/about.htm">About DPS</a></li>
			<li><a href="/contact.htm">Contact Us</a></li>
			<li><a href="/ETR/index.htm">Education, Training & Research</a></li>
			<li><a href="/ETR/fitnessWellnessUnit.htm">Fitness Wellness Info</a></li>
			<li><a href="/geninfo.htm">General Information</a></li>
			<li><a href="/HQmap_austin.htm">Maps to DPS</a></li>
			<li><a href="/medalofvalor.htm">Medal of Valor</a></li>
			<li><a href="/orgchart/OrgChart.pdf">Organization Chart (PDF)</a></li>
			<li><a href="/siteindex.htm">Site Index</a></li>
			<li><a href="/solicitations/">Solicitations</a></li>
			<li><a href="/memorial/">Tribute to Fallen Employees</a></li>
		</ul>
  	</li>
	</ul>	
</nav>
	
<script>dropdown('nav', 'hover', 150);</script> 

<!-- xxxxx ALERT MESSAGE AREA xxxxxxxxxxxxxx -->
<!--<p style="background-color:red; text-align:center; vertical-align; middle; padding: 3px; width:360px; height:55px; color:#ffffff"><strong>ATTENTION:</strong>  Due to technical difficulties, all DPS Contact Centers are currently unable to accept calls. Please check back for status updates</p>-->		
<!--<p style="color:red"><strong>Due to weather concerns, Austin area offices, including<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Driver License offices, will open at 10 AM Wed.,<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Jan. 17th, 2018.  Other offices may be affected<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;as well. Please check with your local office.</strong></p>-->
<!--<p style="color:red; margin-top:2px; font-weight: bold; font-size: 14px;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://gov.texas.gov/hurricane" style="color:red">Visit the TEXAS HURRICANE CENTER webpage for<br /> &nbsp;&nbsp;&nbsp;&nbsp;Hurricane Harvey-related information and resources</a></strong></p>-->
<!--<p style="margin-top:-25px; font-weight: bold; font-size: 16px;"><strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/SunsetAnnouncement.pdf" target="_blank" title="Sunset Announcement">Sunset Announcement</a></strong></p>-->
<!-- xxxxx END of ALERT MESSAGE AREA xxxxxxxxxxxxxx -->
