<table border="0" cellspacing="0" cellpadding="0" width="100%">

  <tr>
	<td width="100%" nowrap bgcolor=#000000><img src="/includes/images/space.gif" alt="" width="1" height="1"></td>
  </tr>
  <tr>
	<td width="100%" nowrap><img src="/includes/images/space.gif" alt="" width="1" height="10"></td>
  </tr>
  <tr> 
    <td width="100%" nowrap align="left"> 
				<a href="/about.htm"><span class=link>About DPS</span></a> | 
				<a href="/geninfo.htm"><span class=link>General DPS Information</span></a> | 
				<a href="/onserv.htm"><span class=link>DPS Online Services</span></a> | 
				<a href="/news.htm"><span class=link>DPS News</span></a> | 
				<a href="/jobs.htm"><span class=link>DPS Employment</span></a> | 
				<a href="/siteindex.htm"><span class=link>DPS Website Site Index</span></a> | 
				<a href="/contact.htm"><span class=link>DPS Contact Information</span></a>
		
	</td>
	<td width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="1"></td>
  </tr>
<tr>
    <td valign="bottom" bgcolor="#FFFFFF"> 
      <div align="left">  <a href="https://webmail.txdps.state.tx.us/exchange" title="Outlook Web Access"><span class=link>Outlook
        Web Access</span></a> |<a href="/pia.htm" title="Public Information Act"><span class=link>Public 
        Information Act</span></a> |<a href="/privacy.htm" title="DPS Privacy Policy"><span class=link> 
        Privacy Policy</span></a> | <a href="/compact/" title="Information about the Agency"><span class=link>Compact 
        with Texans</span></a> | <a href="/director_staff/public_information/openrecords.htm" title="File an Open Records Request"><span class=link>Open 
        Records</span></a> | <a href="/OIG/complaint.htm" title="How to file a complaint"><span class=link>Complaint 
        Process</span></a>  <a href="/director_staff/internal_affairs/complaint-esp.htm" title="Como presentar una queja"><span class=link>Español</span></a></div>
    </td>
    <td width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="1"></td>
  </tr>
  <tr>
	<td width="100%" nowrap><img src="/includes/images/space.gif" alt="" width="1" height="10"></td>
  </tr>  
</table>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
	<td width="100%" nowrap bgcolor=#000000><img src="/includes/images/space.gif" alt="" width="1" height="1"></td>
  </tr>
</table>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
    <td><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#999999"><b>    Visit these related sites.</b></font></td>
  </tr>
</table>

<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr> 
    <td width="216" valign="top"> 
      <div align="center"><a href="http://www.state.tx.us"><img src="/includes/images/state_of_texas_icon.jpg" width="50" height="48" valign="absmiddle" alt="The State of Texas" name="SOT" border="0"></a> 
        <a href="http://www.texasonline.com"><img src="/includes/images/texasonline.gif" width="56" height="48" valign="absmiddle" alt="Texas Online" name="TO" border="0"></a> 
        <a href="http://castor.tsl.state.tx.us/trail/"><img src="/includes/images/trail_icon.gif" width="51" height="27" align="absmiddle" name="TRAIL" alt="Texas Records and Information Locator" border="0"></a> 
        <br>
        <a href="http://www.dot.state.tx.us/"><img src="/includes/images/txdot_icon.gif" width="50" height="48" name="txdot" alt="Texas Department of Transportation Customer Service" border="0"></a> 
        <a href="http://www.tea.state.tx.us/drive/"><img src="/includes/images/txed_icon.gif" width="50" height="48" name="txed" alt="Texas Education Agency Driver Training and Education" border="0"></a></div>
    </td>
    <td valign="top" width="544"> 
      <div align="center"> 
        <p><font face="Verdana, Arial, Helvetica, sans-serif" size="1" color="#000000"> 
          Texas Department of Public Safety 5805 North Lamar Blvd. Austin, Texas 
          78752-4422 <br>
          P O Box 4087 Austin, Texas 78773-0001<br>
          (512) 424-2000<br>
          © 2000Texas Department of Public Safety. <br>
         <br><b>If an employee or division provided outstanding service or if you have suggestions for improvement, please let us know.  
           Take our <a href="http://www.survey.utexas.edu/txdps/" target="_blank">Customer 
          Survey</a>.</b> </font></p>
        <table width="400" border="0" cellspacing="0" cellpadding="0" align="center">
          <tr>
            <td><font face="Verdana, Arial, Helvetica, sans-serif" size="1" color="#000000">
              <p align="left"><font face="Verdana, Arial, Helvetica, sans-serif" size="1" color="#000000">Pursuant 
                to Section 552.301(c), Government Code, the <a href="/director_staff/public_information/">Public 
                Information Office</a> has been designated to receive all electronic 
                mail requests for public information. The Department is not responsible 
                for responding to electronic mail requests sent to any electronic 
                mail address other than the address for the public information 
                office.</font></p>
              </font> </td>
          </tr>
          <tr><td><p>&nbsp;</p></td></tr>
        </table>
        </div>
    </td>
  </tr>
</table>
