<div align="center">
<br>
<a class=darkbluelink href = "#" onClick = 'window.open("/help.htm","help",config="height=450, width=400, toolbar=no, menubar=no, scrollbars=yes, resizable=no, location=no, directories=no, status=no");'>Help | </a> 
<a class=darkbluelink href = "#" onClick = 'window.open("/faq.htm","faq",config="height=450, width=400, toolbar=no, menubar=no, scrollbars=yes, resizable=no, location=no, directories=no, status=no");'>FAQs | </a>
<a class=darkbluelink href="http://dpsnet/help/index.asp">Feedback</a></p>
</div>

