
<div style="text-align:center" id="footDiv" class="footDiv">
<img id="footSeperator" class="sepImage" src="/images/txseperatorwide.png" alt="" width="720" height="20"/>
<br />
<strong>Note:</strong> links to [PDF] files require <a href="https://get.adobe.com/reader/">Adobe Reader</a> or another PDF viewer. 
<br />
<br />

| 
 <a href="/administration/staff_support/human_resources/ADA.htm">Accessibility</a> | <a href="/SitePolicies.htm">Site Policies</a> | 
 <a href="https://www.tsl.texas.gov/trail/index.html">TRAIL</a> | <a href="https://sao.fraud.texas.gov/">Report Fraud, Waste or Abuse</a> | 
<br/>
|  
 <a href="https://outlook.com/owa/dps.texas.gov">Outlook Web App</a> |  <a href="http://gov.texas.gov/">Texas Homeland Security</a> | 
 <a href="/pia.htm">Public Information Act</a> |  <a href="/compact/">Compact with Texans</a> | 
<br/>
| 
 <a href="http://gov.texas.gov/disabilities/">The Governor's Committee on People with Disabilities</a> |  
 <a href="https://survey.utexas.edu/dld">Customer Survey</a> | 
 <a href="https://veterans.portal.texas.gov/"> Texas Veterans Portal</a> | <br/>
| <a href="/docs/TxFCPrivacyPolicy113010.pdf"> Texas Fusion Center Privacy Policy</a> | <a href="http://www.texas.gov"> texas.gov</a> |
 <a href="https://olympus.soc.texas.gov/services/OSTCostReport/"> ERR Entry</a> |   <a href="https://erpprtlprd.cpa.texas.gov/"> CAPPS Login</a> |
 <br />
</div>

<div >
	<br />
	<p>&copy; 2000-2018 Texas Department of Public Safety. </p>

</div>