
<div id="footDiv" class="footDiv" align="center" lang="en">
<img id="footSeperator" class="sepImage" src="/images/txseperatorwide.png" alt="null"/><br />
<strong>Note:</strong> links to [PDF] files require <a href="http://get.adobe.com/reader/" title="Adobe" target="_blank">Adobe Reader</a> or another PDF viewer. <br /><br />

 |
<a href="http://www.dps.texas.gov/administration/staff_support/human_resources/ADA.htm">Accessibility</a> |
<a href="http://www.dps.texas.gov/SitePolicies.htm">Site Policies</a> | 
<a href="http://www.tsl.state.tx.us/trail" title="Texas Records And Information Locator" target="_blank">TRAIL</a> | 
<a href="http://tsiec.region49.org/" title="Texas State Interoperability Executive Committee" target="_blank">TSIEC</a>  |
<a href="https://sao.fraud.state.tx.us/hotline.aspx">Report Fraud, Waste or Abuse</a> | 
<a href="http://www.recovery.gov/Pages/default.aspx">American Recovery and Reinvestment ACT </a> | 
<br/>
 
<a href="http://webmail.dps.texas.gov" title="Outlook Web Access">Outlook Web Access</a> | 
<a href="https://time.cpa.texas.gov/dpstk/login.jsp" title="ETA Time Entry" target="_blank">ETA Time Entry</a> |
<a href="http://www.texashomelandsecurity.com/" title="Texas Homeland Security" target="_blank">Texas Homeland Security</a> |
<a href="http://www.dps.texas.gov/pia.htm" title="Public Information Act">Public Information Act</a> |
<a href="http://www.dps.texas.gov/compact/" title="Information about the Agency">Compact with Texans</a> |
<br/>
<a href="http://www.governor.state.tx.us/disabilities/" title="The Governor's Committee on People with Disabilities">The Governor's Committee on People with Disabilities</a> 
| <a href="http://www.dps.texas.gov/OIG/complaint.htm" title="How to file a complaint against specific DPS personnel">Personnel Complaint Process</a>  <a href="http://www.dps.texas.gov/OIG/complaint-esp.htm">(Espanol)</a>  |
 <a href="http://www.survey.utexas.edu/txdps/" title="Please take our quick Survey" target="_blank">Customer Survey</a> |<br />
| <a href="http://veterans.portal.texas.gov/en/Pages/default.aspx"  target="_blank" title="opens a new window"> Texas Veterans Portal</a> |<a href="http://www.dps.texas.gov/docs/TxFCPrivacyPolicy113010.pdf"  target="_blank" title="Texas Fusion Center Privacy Policy"> Texas Fusion Center Privacy Policy</a> |<a href="http://www.texas.gov"  target="_blank" title="texas.gov"> texas.gov</a> |<a href="https://olympus.soc.texas.gov/services/OSTCostReport/"  target="_blank" title="OSS Entry"> OST Entry</a> | <a href="prea.htm" target ="blank" title="PREA">PREA</a><br />
</div>
<div ><br />
<p>&copy; 2000-2011 Texas Department of Public Safety. </p>

</div>