<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
    <td valign="top" rowspan="7" width="135"><img src="/includes/images/logo.gif" width="135" height="100" alt="Department of Public Safety Logo" name="logo"></td> 
    <td valign="top" rowspan="6" width="625"><img src="/includes/images/banner.gif" width="625" height="55" alt="Texas Department of Public Safety - courtesy - service - protection" name="DPSbanner"></td>
    <td valign="top" bgcolor="#CC0000" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="28"></td>
</tr>
<tr><td valign="top" bgcolor="#FFFFFF" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="2"></td></tr>
<tr><td valign="top" bgcolor="#808080" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="2"></td></tr>
<tr><td valign="top" bgcolor="#CC0000" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="2"></td></tr>
<tr><td valign="top" bgcolor="#808080" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="13"></td></tr>
<tr><td valign="top" bgcolor="#CC0000" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="8"></td></tr>
<tr>
    <td valign="top" width="625" bgcolor="#FFFFFF"> <a href="/"><img src="/includes/images/1home.gif" border=0 align=middle alt="DPS Home Page"></a> 
      <a href="/about.htm"><img src="/includes/images/1about.gif" border=0 align=middle alt="About DPS"></a> 
      <a href="/geninfo.htm"><img src="/includes/images/1geninfo.gif" border=0 align=middle alt="General Information"></a> 
      <a href="/onserv.htm"><img src="/includes/images/1onlineserv.gif" border=0 align=middle alt="Online Services"></a> 
      <a href="/news.htm"><img src="/includes/images/1news.gif" border=0 align=middle alt="DPS News"></a>
      <a href="/jobs.htm"><img src="/includes/images/1jobs.gif" border=0 align=middle alt="Employment Opportunities"></a> 
	  <a href="http://survey.utexas.edu/txdps/" target="_blank"><img src="/includes/images/1onlinesurv.gif" border=0 align=middle alt="Online Survey"></a> 
      <SCRIPT LANGUAGE="JavaScript1.2">
<!--
//For IE
if (document.all) {
    loadMenus();
}
//-->
</SCRIPT>
    </td>
    <td valign="top" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="45"></td>
</tr>
</table>
<table border="0" cellspacing="0" cellpadding="0" width="100%">
  <tr>
    <td valign="top" width="10"><img src="/includes/images/space.gif" alt="" width="760" height="5"></td>
    <td valign="top" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="5"></td>
  </tr>
  <tr>
    <td valign="top" bgcolor="#CC0000" width="10"><img src="/includes/images/space.gif" alt="" width="760" height="2"></td>
    <td valign="top" bgcolor="#CC0000" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="2"></td>
  </tr>
  <tr>
    <td valign="top" bgcolor="#FFFFFF" width="10"><img src="/includes/images/space.gif" alt="" width="760" height="1"></td>
    <td valign="top" bgcolor="#FFFFFF" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="1"></td>
  </tr>
  <tr>
    <td valign="top" bgcolor="#999999" width="10"><img src="/includes/images/space.gif" alt="" width="760" height="1"></td>
    <td valign="top" bgcolor="#999999" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="1"></td>
  </tr>
  <tr>
    <td valign="top" bgcolor="#CC0000" width="10"><img src="/includes/images/space.gif" alt="" width="760" height="2"></td>
    <td valign="top" bgcolor="#CC0000" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="2"></td>
  </tr>
  <tr>
    <td valign="top" width="10"><img src="/includes/images/space.gif" alt="" width="760" height="10"></td>
    <td valign="top" width="100%"><img src="/includes/images/space.gif" alt="" width="1" height="10"></td>
  </tr>
</table>
