<%
'this is used to set up the connection object and its connection string

'Dim MM_conn_STRING
'MM_conn_STRING = "PROVIDER=SQLOLEDB; DATA SOURCE=PRDSQLCLUS02K\K; INITIAL CATALOG=MPCH; USER ID=9GE41V27; PASSWORD=Za8E5HaC;"
Dim MM_conn_STRING
MM_conn_STRING = "PROVIDER=SQLOLEDB; DATA SOURCE=TSTSQLCLUS01E; INITIAL CATALOG=MPCH; USER ID=9GE41V27; PASSWORD=nu+ra3He;"

%>