<div>
<hr width="95%"/>

<div align="center">

<a href="/about.htm">About DPS</a> | 
<a href="/geninfo.htm">General DPS Information</a> | 
<a href="/onserv.htm">DPS Online Services</a> | 
<a href="/jobs.htm">DPS Employment</a> | 
<a href="/siteindex.htm">DPS Website Site Index</a> | <a href="/contact.htm">DPS Contact Information</a> | 
<a href="http://tsiec.region49.org/">TSIEC</a><br />

<a href="https://webmail.txdps.state.tx.us/exchange" title="Outlook Web Access">Outlook Web Access</a> |
<a href="/pia.htm" title="Public Information Act">Public Information Act</a> |
<a href="/privacy.htm" title="DPS Privacy Policy">Privacy Policy</a> |
<a href="/compact/" title="Information about the Agency">Compact with Texans</a> | 
<a href="/director_staff/public_information/openrecords.htm" title="File an Open Records Request">OpenRecords</a> | 
<a href="/OIG/complaint.htm" title="How to file a complaint">ComplaintProcess</a><a href=
"/director_staff/internal_affairs/complaint-esp.htm" title=
"Como presentar una queja"> - Español</a>
</div>
<hr width="95%"/>
<br />


<p align="center">Texas Department of Public Safety
5805 North Lamar Blvd. Austin, Texas 78752-4422 <br />
 P O Box 4087 Austin, Texas 78773-0001<br />
 (512) 424-2000<br />
© 2000Texas Department of Public Safety.
<br />
<br />
 If an employee or division provided outstanding service<br />
 or if you have suggestions for improvement, please let us know.
Take our <a href="http://www.survey.utexas.edu/txdps/" target="_blank">Customer Survey.</a></p>


<p align="center">Pursuant to Section 552.301(c),Government Code, the <a href="/director_staff/public_information/">Public Information Office</a> has been designated to receive all electronic mail requests for
public information. <br />
The Department is not responsible for
responding to electronic mail requests sent to any electronic mail
address other than the address for the public information
office.</p>
<br />
<br />
</div>
