<link rel="stylesheet" type="text/css" href="/includes/styles/hstyle.css">

<!--[if IE]>
<STYLE type=text/css media=screen>
body {
behavior: url(/includes/csshover.htc);
font-size: 100%;
} 
#menu ul li {float: left; width: 100%;}
#menu ul li a {height: 1%;} 

#menu a, #menu h2 {
font: bold 0.7em/1.2em arial, helvetica, sans-serif;
} 
</STYLE>
<![endif]-->

<link rel="stylesheet" type="text/css" href="/includes/styles/dpsnetstyles.css">

