
<div id="topNavBox" style="
						position: absolute; 
						  color: #fefefe; 
						  width:640px; 
						  left: 106px; 
						  top: 60px; 
						  z-index:1;">

<ul id="topNavList">
<li style= "border-left-style: none;"><a href="/index.htm"> <strong>Main Page </strong></a></li>
<li><a href="/siteindex.htm"><strong>Site Index</strong> </a></li>
<li><a href="/onserv.htm"> <strong>Online Services</strong> </a></li>
<li><a href="/administration/staff_support/human_resources/jobs/jobsearch.asp"> <strong>Employment </strong></a></li>
<li><a href="/news.htm"> <strong>News</strong> </a></li>
<li><a href="/index_sp.htm"> <strong>Spanish</strong></a></li>
</ul>
</div>


